// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAee_lYhb0oEwU_XSqhWaGfxfVJbESAsAc',
    appId: '1:146734299654:web:26a02743904df8c061e187',
    messagingSenderId: '146734299654',
    projectId: 'example-auth-1',
    authDomain: 'example-auth-1.firebaseapp.com',
    storageBucket: 'example-auth-1.appspot.com',
    measurementId: 'G-5HVPEQJKKX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjJZXLHO7PaO4r2k69NDZXs4jU1qJSuX4',
    appId: '1:146734299654:android:e130334b52d3576e61e187',
    messagingSenderId: '146734299654',
    projectId: 'example-auth-1',
    storageBucket: 'example-auth-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd1o8UIZ1KWSb5Pgu3cqL5R9i4aQb_uxs',
    appId: '1:146734299654:ios:3566133f8fb4a9a861e187',
    messagingSenderId: '146734299654',
    projectId: 'example-auth-1',
    storageBucket: 'example-auth-1.appspot.com',
    androidClientId: '146734299654-b9akskvvv92ei7olohbvm529k0csa5s3.apps.googleusercontent.com',
    iosClientId: '146734299654-c9i3lt4h6vjijubajc55nsn6tdt0cei9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterStorageExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDd1o8UIZ1KWSb5Pgu3cqL5R9i4aQb_uxs',
    appId: '1:146734299654:ios:3566133f8fb4a9a861e187',
    messagingSenderId: '146734299654',
    projectId: 'example-auth-1',
    storageBucket: 'example-auth-1.appspot.com',
    androidClientId: '146734299654-b9akskvvv92ei7olohbvm529k0csa5s3.apps.googleusercontent.com',
    iosClientId: '146734299654-c9i3lt4h6vjijubajc55nsn6tdt0cei9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterStorageExample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAee_lYhb0oEwU_XSqhWaGfxfVJbESAsAc',
    appId: '1:146734299654:web:26a02743904df8c061e187',
    messagingSenderId: '146734299654',
    projectId: 'example-auth-1',
    authDomain: 'example-auth-1.firebaseapp.com',
    storageBucket: 'example-auth-1.appspot.com',
    measurementId: 'G-5HVPEQJKKX',
  );

}